### ISSUE TITLE
Concurrent map read and map write in MapClaims

### ISSUE THREAD

**Issue by AdrianLungu** [dgrijalva/jwt-go#169]
Hello,

I've been experimenting with HTTP/2 recently and I'm not sure if the fact that it allows simultaneous connections or some other problem is at hand, but I've been running into random occasional concurrent map read and write fatal errors:

```
fatal error: concurrent map read and map write

goroutine 333 [running]:
runtime.throw(0x5664b5, 0x21)
        /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc4203ab2b0 sp=0xc4203ab290
runtime.mapaccess1_faststr(0x515600, 0xc420178090, 0x5531b9, 0x3, 0xc4204a6201)
        /usr/local/go/src/runtime/hashmap_fast.go:201 +0x4f3 fp=0xc4203ab310 sp=0xc4203ab2b0
github.com/dgrijalva/jwt-go.MapClaims.VerifyIssuedAt(0xc420178090, 0x57cf5add, 0x7c2200, 0xc4203ab301)
        /Users/adrianlungu/IdeaProjects/go/src/github.com/dgrijalva/jwt-go/map_claims.go:36 +0x58 fp=0xc4203ab378 sp=0xc4203ab310
github.com/dgrijalva/jwt-go.MapClaims.Valid(0xc420178090, 0xc42046e450, 0xc420270060)
        /Users/adrianlungu/IdeaProjects/go/src/github.com/dgrijalva/jwt-go/map_claims.go:79 +0x9f fp=0xc4203ab3d0 sp=0xc4203ab378
github.com/dgrijalva/jwt-go.(*Parser).ParseWithClaims(0xc4203ab5c8, 0xc4201303c7, 0xb7, 0x78dd60, 0xc420178090, 0xc4201f2480, 0x6, 0xc42024b5f8, 0x1f7f8)
        /Users/adrianlungu/IdeaProjects/go/src/github.com/dgrijalva/jwt-go/parser.go:106 +0x8ed fp=0xc4203ab580 sp=0xc4203ab3d0
github.com/dgrijalva/jwt-go.ParseWithClaims(0xc4201303c7, 0xb7, 0x78dd60, 0xc420178090, 0xc4201f2480, 0x0, 0xc41fff8dd9, 0xc42024b6e0)
        /Users/adrianlungu/IdeaProjects/go/src/github.com/dgrijalva/jwt-go/token.go:93 +0x8f fp=0xc4203ab5f8 sp=0xc4203ab580
github.com/labstack/echo/middleware.JWTWithConfig.func1.1(0x798cc0, 0xc42045e000, 0x7c22c0, 0x0)
        /Users/adrianlungu/IdeaProjects/go/src/github.com/labstack/echo/middleware/jwt.go:132 +0x257 fp=0xc4203ab6e0 sp=0xc4203ab5f8
adrianlungu.com/goapp/vendor/goapp/middleware.LoggerWithConfig.func2.1(0x798cc0, 0xc42045e000, 0x0, 0x0)
        /Users/adrianlungu/IdeaProjects/go/src/adrianlungu.com/goapp/vendor/goapp/middleware/logger.go:84 +0x119 fp=0xc4203ab7b0 sp=0xc4203ab6e0
github.com/labstack/echo.(*Echo).add.func1(0x798cc0, 0xc42045e000, 0xc42046c360, 0x78dee0)
        /Users/adrianlungu/IdeaProjects/go/src/github.com/labstack/echo/echo.go:474 +0x96 fp=0xc4203ab7f0 sp=0xc4203ab7b0
github.com/labstack/echo/middleware.GzipWithConfig.func1.1(0x798cc0, 0xc42045e000, 0x0, 0x0)
        /Users/adrianlungu/IdeaProjects/go/src/github.com/labstack/echo/middleware/compress.go:88 +0x21b fp=0xc4203ab8b0 sp=0xc4203ab7f0
github.com/labstack/echo/middleware.CORSWithConfig.func1.1(0x798cc0, 0xc42045e000, 0xf, 0x5589db)
        /Users/adrianlungu/IdeaProjects/go/src/github.com/labstack/echo/middleware/cors.go:107 +0x340 fp=0xc4203ab9b8 sp=0xc4203ab8b0
github.com/labstack/echo/middleware.SecureWithConfig.func1.1(0x798cc0, 0xc42045e000, 0xc4201f6230, 0x4d60c0)
        /Users/adrianlungu/IdeaProjects/go/src/github.com/labstack/echo/middleware/secure.go:113 +0x35c fp=0xc4203aba88 sp=0xc4203ab9b8
github.com/labstack/echo/middleware.BodyLimitWithConfig.func1.1(0x798cc0, 0xc42045e000, 0x0, 0x0)
        /Users/adrianlungu/IdeaProjects/go/src/github.com/labstack/echo/middleware/body_limit.go:87 +0x20f fp=0xc4203abae8 sp=0xc4203aba88
github.com/labstack/echo/middleware.RecoverWithConfig.func1.1(0x798cc0, 0xc42045e000, 0x0, 0x0)
        /Users/adrianlungu/IdeaProjects/go/src/github.com/labstack/echo/middleware/recover.go:82 +0x124 fp=0xc4203abb40 sp=0xc4203abae8
github.com/labstack/echo.(*Echo).ServeHTTP.func1(0x798cc0, 0xc42045e000, 0x22, 0x0)
        /Users/adrianlungu/IdeaProjects/go/src/github.com/labstack/echo/echo.go:555 +0x154 fp=0xc4203abbc0 sp=0xc4203abb40
github.com/labstack/echo/middleware.HTTPSRedirectWithConfig.func1.1(0x798cc0, 0xc42045e000, 0xc42006c188, 0xca0398)
        /Users/adrianlungu/IdeaProjects/go/src/github.com/labstack/echo/middleware/redirect.go:60 +0x183 fp=0xc4203abc60 sp=0xc4203abbc0
github.com/labstack/echo.(*Echo).ServeHTTP(0xc4201a61e0, 0x796740, 0xc420076040, 0x795180, 0xc4201bc1e0)
        /Users/adrianlungu/IdeaProjects/go/src/github.com/labstack/echo/echo.go:564 +0x1e5 fp=0xc4203abcb8 sp=0xc4203abc60
github.com/labstack/echo/engine/standard.(*Server).ServeHTTP(0xc4200a1580, 0x7923a0, 0xc420080098, 0xc4203ca780)
        /Users/adrianlungu/IdeaProjects/go/src/github.com/labstack/echo/engine/standard/server.go:140 +0x33c fp=0xc4203abd20 sp=0xc4203abcb8
net/http.serverHandler.ServeHTTP(0xc4200a1480, 0x7923a0, 0xc420080098, 0xc4203ca780)
        /usr/local/go/src/net/http/server.go:2202 +0x7d fp=0xc4203abd68 sp=0xc4203abd20
net/http.initNPNRequest.ServeHTTP(0xc4202d6380, 0xc4200a1480, 0x7923a0, 0xc420080098, 0xc4203ca780)
        /usr/local/go/src/net/http/server.go:2670 +0x93 fp=0xc4203abed0 sp=0xc4203abd68
net/http.(*initNPNRequest).ServeHTTP(0xc4202c2150, 0x7923a0, 0xc420080098, 0xc4203ca780)
        <autogenerated>:288 +0x79 fp=0xc4203abf10 sp=0xc4203abed0
net/http.(Handler).ServeHTTP-fm(0x7923a0, 0xc420080098, 0xc4203ca780)
        /usr/local/go/src/net/http/h2_bundle.go:4084 +0x4d fp=0xc4203abf40 sp=0xc4203abf10
net/http.(*http2serverConn).runHandler(0xc4203c4000, 0xc420080098, 0xc4203ca780, 0xc42049e6e0)
        /usr/local/go/src/net/http/h2_bundle.go:4314 +0x89 fp=0xc4203abf80 sp=0xc4203abf40
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4203abf88 sp=0xc4203abf80
created by net/http.(*http2serverConn).processHeaders
        /usr/local/go/src/net/http/h2_bundle.go:4092 +0x6e2

```

A little digging around pointed me to the fact that maps are not thread-safe, could that be the issue at hand ?

Thanks!

**Comment by dgrijalva** [comment]
It is true that maps are not thread safe.  More specifically, they are safe to read concurrently, but not write.  AFAIK, there's nothing in the parse/verify code that's likely to incur concurrency related issues, since there aren't shared objects.  That said, the `Token`s that it produces don't have any access protection built in.  The offending line in your crash dump is just a map read.  Are you maybe writing to the claims map in another goroutine?

**Comment by dgrijalva** [comment]
I'd encourage you to not mutate a parsed token, in general, but you can do so safely with correct use of `sync.RWMutex`, etc.

**Comment by AdrianLungu** [comment]
It's pretty hard to say specifically what's producing the issue since I can't constantly reproduce it, it happens every once in a while. 

I'm only using the library to create a new token when a user logs in (but this is not called when the issue occurs) and through LabStack Echo's JWT middleware on which I call the following code to get the User's ID: 

```
func GetUserIdFromToken(c echo.Context) int {

	user := c.Get("user").(*jwt.Token)
	claims := user.Claims.(jwt.MapClaims)
	id := claims[`id`]

	switch id.(type) {
	case float64:
		return int(id.(float64))
	case float32:
		return int(id.(float32))
	case int32, int64, int:
		return id.(int)
	default:
		return 0
	}

}
```

This particular piece of code could end up being called concurrently due to how my frontend checks if a user is signed in.

Other than that, there's nothing that would mutate a token.

**Comment by dgrijalva** [comment]
Are you maybe accidentally reusing a map somewhere?

**Comment by AdrianLungu** [comment]
Not that I'm aware of, this is what I use to create the Token when logging in:

```
token := jwt.New(jwt.SigningMethodHS256)

	claims := token.Claims.(jwt.MapClaims)
	claims[`firstName`] = user.FirstName
	claims[`id`] = user.Id
	claims[`nbf`] = time.Now().Unix()
	claims[`iss`] = "goapp"
	claims[`exp`] = time.Now().Add(time.Hour * 72).Unix()

	signedToken, err := token.SignedString(self.jwtSecret)
	if err != nil {
		return err
	}
```

And the Echo middleware seems to only call `ParseWithClaims` from jwt.go. 

These are the only instances in which jwt.go is called.

**Comment by dgrijalva** [comment]
The code in the crash is definitely a read.  Concurrent reads are ok: http://stackoverflow.com/questions/11063473/map-with-concurrent-access

Have a look at the other routines in your crash.  Is one of them writing to a map?

**Comment by dgrijalva** [comment]
You could rewrite this part as 
```go
token.Claims = jwt.MapClaims{
  "firstName": user.FirstName,
  // etc
}
```

I don't think it would make a difference, though.

**Comment by AdrianLungu** [comment]
![screen shot 2016-09-07 at 03 50 38](https://cloud.githubusercontent.com/assets/1700129/18295950/7b314e7c-74ae-11e6-9580-ae1e23e6d7f1.png)

This is all I could find in the project. I'll investigate further to try to reproduce it constantly and see what makes it happen.

**Comment by dgrijalva** [comment]
Look for `claims[.*] =` to see where any other assignments are happening.  Maybe also look into that middleware package to see what they're doing.  Can you capture a full crash dump?  You can find my public key here (https://keybase.io/dgrijalva) if there's anything you don't want to post publicly.  That said, please don't send me anything sensitive (keys for example).

**Comment by dgrijalva** [comment]
I think there may be a concurrency issue with https://github.com/labstack/echo/blob/master/middleware/jwt.go.

It looks like the same claims object is used every time `ParseWithClaims` is called.  `middleware.JWTWithConfig` is being called concurrently with a nil `Claims` property, you can have a crash.

**Comment by dgrijalva** [comment]
It's hard to know exactly what's happening.  I'm just walking backwards through your stack trace.  I'd wager this is it though.  I opened an issue with the author of that library: https://github.com/labstack/echo/issues/647

**Comment by AdrianLungu** [comment]
Managed to reproduce the error by bombarding the server with requests. It seems your recommendation helped them patch it up and it's no longer throwing that error when being bombarded with concurrent requests! Thanks!

**Comment by dgrijalva** [comment]
Glad I could be helpful.  Closing this ticket.  Feel free to reopen if you feel I've closed it prematurely.
